# Exported from Render on 2024-07-09T18:30:53Z
services:
- type: web
  name: major-project
  env: node
  plan: free
  buildCommand: npm install
  startCommand: node index.js
  envVars:
  - key: ATLASDB_URL
    value: mongodb+srv://nakul744:ebFlAk5ipkEEkJhZ@cluster0.lojfcip.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  - key: CLOUD_API_KEY
    value: "211142596471654"
  - key: CLOUD_API_SECRET
    value: TZdGUNTxW_YgaWXCu7HGWEPl-9M
  - key: CLOUD_NAME
    value: dhwglxnwe
  - key: MAP_TOKEN
    value: pk.eyJ1IjoiaXRzc2FyYW5oZXJlIiwiYSI6ImNsd3B3aDFybjFodTMyaXJ6cGQxeWdwYzcifQ.4HPJRlRvgTdHaXXTDQEWCg
  - key: SECRET
    value: sdnascnajscasasncassgit config core.autocrlf true
  region: oregon
version: "1"
